[2023-12-13T12:14:03.058+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tafmis_test_data_fetch.get_token manual__2023-12-13T12:14:01.007462+00:00 [queued]>
[2023-12-13T12:14:03.069+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tafmis_test_data_fetch.get_token manual__2023-12-13T12:14:01.007462+00:00 [queued]>
[2023-12-13T12:14:03.069+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-12-13T12:14:03.084+0000] {taskinstance.py:1382} INFO - Executing <Task(_PythonDecoratedOperator): get_token> on 2023-12-13 12:14:01.007462+00:00
[2023-12-13T12:14:03.093+0000] {standard_task_runner.py:57} INFO - Started process 119 to run task
[2023-12-13T12:14:03.098+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'tafmis_test_data_fetch', 'get_token', 'manual__2023-12-13T12:14:01.007462+00:00', '--job-id', '15', '--raw', '--subdir', 'DAGS_FOLDER/tafmis_test.py', '--cfg-path', '/tmp/tmp05d_t5y1']
[2023-12-13T12:14:03.100+0000] {standard_task_runner.py:85} INFO - Job 15: Subtask get_token
[2023-12-13T12:14:03.174+0000] {task_command.py:416} INFO - Running <TaskInstance: tafmis_test_data_fetch.get_token manual__2023-12-13T12:14:01.007462+00:00 [running]> on host 67519c681eff
[2023-12-13T12:14:03.262+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='tafmis_test_data_fetch' AIRFLOW_CTX_TASK_ID='get_token' AIRFLOW_CTX_EXECUTION_DATE='2023-12-13T12:14:01.007462+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-12-13T12:14:01.007462+00:00'
[2023-12-13T12:14:03.263+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 221, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/tafmis_test.py", line 20, in get_token
    token_url = token_url
UnboundLocalError: local variable 'token_url' referenced before assignment
[2023-12-13T12:14:03.273+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=tafmis_test_data_fetch, task_id=get_token, execution_date=20231213T121401, start_date=20231213T121403, end_date=20231213T121403
[2023-12-13T12:14:03.286+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 15 for task get_token (local variable 'token_url' referenced before assignment; 119)
[2023-12-13T12:14:03.311+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-13T12:14:03.341+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
